version: 3.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: >-
    nuget restore

    dotnet restore
build:
  project: LandmarkDevs UI Library.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: Sn4vP+KGBcfWC2DLL6Sxxol/bU5W0XPfxJ60k3bTUPMtnJ7QW63R2GmuaQB/T9Nk
notifications:
- provider: Email
  to:
  - tim@landmarkdevs.com
  subject: '[AppVeyor] LandmarkDevs UI Library Build Success'
  message: LandmarkDevs UI Library has been built successfully.
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
- provider: Email
  to:
  - tim@landmarkdevs.com
  subject: '[AppVeyor] LandmarkDevs UI Library Build Failed'
  message: LandmarkDevs UI Library has failed to build.
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
